# Generated by Django 6.0.7 on 2026-07-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='phone_no',
            field=models.BigIntegerField(),
        ),
    ]
