# Generated by Django 6.0.7 on 2026-07-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_shortfilm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortfilm',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
