# Generated by Django 6.0.7 on 2026-08-13 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_shortfilm_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchLater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('shortfilm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.shortfilm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.register')),
            ],
            options={
                'db_table': 'watch_later',
                'unique_together': {('user', 'shortfilm')},
            },
        ),
    ]
